version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  mariadb1:
    build: ./mariadb_custom
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: catdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb1-data:/var/lib/mysql

  mariadb2:
    build: ./mariadb_custom
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: catdb
    ports:
      - "3307:3306"
    volumes:
      - mariadb2-data:/var/lib/mysql

  maxscale:
    image: mariadb/maxscale:latest
    environment:
      - MAXSCALE_USER=maxuser
      - MAXSCALE_PASSWORD=max
