version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  mariadb1:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: catdb
    ports:
      - "3308:3309"
    volumes:
      - mariadb1-data:/var/lib/mysql

  mariadb2:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: catdb
    ports:
      - "3307:3306"
    volumes:
      - mariadb2-data:/var/lib/mysql

  maxscale:
    image: mariadb/maxscale:latest
    environment:
      - MAXSCALE_USER=maxuser
      - MAXSCALE_PASSWORD=maxpwd
    ports:
      - "4000:4000"
      - "3308:3306"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf

  loadbalancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - "8080:8080"
    command: ["start-dev"]

volumes:
  mariadb1-data:
  mariadb2-data:

